services:
  - type: worker
    name: flamekeeper-bot
    rootDir: bot
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
